"use client";

import {
  createContext,
  useContext,
  type CSSProperties,
  type ImgHTMLAttributes,
  type ReactNode,
} from "react";
import type { Darkroom } from "./core/darkroom.js";
import type { ResponsiveSet } from "./core/types.js";

// ---------------------------------------------------------------------------
// Context — provide a Darkroom instance to the component tree
// ---------------------------------------------------------------------------

const DarkroomContext = createContext<Darkroom | null>(null);

/** Provide a {@link Darkroom} instance to descendant components. */
export function DarkroomProvider({
  darkroom,
  children,
}: {
  darkroom: Darkroom;
  children: ReactNode;
}) {
  return (
    <DarkroomContext.Provider value={darkroom}>
      {children}
    </DarkroomContext.Provider>
  );
}

/**
 * Access the nearest {@link Darkroom} instance.
 *
 * @throws If used outside a `<DarkroomProvider>`.
 */
export function useDarkroom(): Darkroom {
  const ctx = useContext(DarkroomContext);
  if (!ctx) {
    throw new Error(
      "useDarkroom() must be used inside a <DarkroomProvider>.",
    );
  }
  return ctx;
}

// ---------------------------------------------------------------------------
// <Picture /> — render a responsive <picture> from a ResponsiveSet
// ---------------------------------------------------------------------------

export interface PictureProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, "src"> {
  /** A {@link ResponsiveSet} produced by `darkroom.responsive()`. */
  src: ResponsiveSet;
  alt: string;
  /** Optional fallback `src` URL used on the inner `<img>`. */
  fallbackSrc?: string;
}

/**
 * Renders a responsive `<picture>` element from a {@link ResponsiveSet}.
 *
 * ```tsx
 * <Picture src={responsiveSet} alt="Hero" />
 * ```
 */
export function Picture({ src: rset, alt, fallbackSrc, ...imgProps }: PictureProps) {
  return (
    <picture>
      {rset.sources.map((source) => (
        <source
          key={source.format}
          type={source.type}
          srcSet={source.srcset}
          sizes={rset.sizes}
        />
      ))}
      <img
        src={fallbackSrc}
        srcSet={rset.srcset}
        sizes={rset.sizes}
        alt={alt}
        {...imgProps}
      />
    </picture>
  );
}

// ---------------------------------------------------------------------------
// <BlurImage /> — image with blur-up placeholder animation
// ---------------------------------------------------------------------------

export interface BlurImageProps extends ImgHTMLAttributes<HTMLImageElement> {
  /** The actual image `src`. */
  src: string;
  /** Base64 data URI generated by `darkroom.placeholder()`. */
  placeholder: string;
  alt: string;
  /** Transition duration in milliseconds. Defaults to 500. */
  transitionMs?: number;
}

/**
 * Displays an image with a blur-up placeholder animation.
 *
 * While the full image loads, the tiny blurred placeholder is shown. Once
 * loaded, a CSS transition reveals the sharp image.
 *
 * ```tsx
 * <BlurImage src="/photo.jpg" placeholder={blurDataUrl} alt="Photo" />
 * ```
 */
export function BlurImage({
  src,
  placeholder,
  alt,
  transitionMs = 500,
  style,
  ...rest
}: BlurImageProps) {
  const wrapperStyle: CSSProperties = {
    position: "relative",
    overflow: "hidden",
    display: "inline-block",
    ...style,
  };

  const placeholderStyle: CSSProperties = {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    filter: "blur(20px)",
    transform: "scale(1.1)",
  };

  const imgStyle: CSSProperties = {
    display: "block",
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: `opacity ${transitionMs}ms ease-in-out`,
  };

  return (
    <span style={wrapperStyle}>
      {/* Low-res placeholder */}
      <img src={placeholder} alt="" aria-hidden style={placeholderStyle} />
      {/* Full image — opacity is toggled via onLoad */}
      <img
        src={src}
        alt={alt}
        style={{ ...imgStyle, opacity: 0 }}
        onLoad={(e) => {
          (e.currentTarget as HTMLImageElement).style.opacity = "1";
        }}
        {...rest}
      />
    </span>
  );
}
